import "./global.css";
import Provider from "./provider";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Barter Seller",
  description: "Generated by create-nx-workspace",
};

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "400", "500", "600", "700", "900"],
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen bg-slate-900 antialiased ${inter.variable}`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
